title: Maxim Joseau - Software Engineer
description: >- # this means to ignore newlines until "baseurl:"
  I'm Maxim Joseau, a Ruby on Rails developer graduated from computer engineering school currently working as a Backend developer for Ouidou.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title

author:
  name: Maxim Joseau
  email: "maxim.joseau@gmail.com"
  github_username: yhru
  bio: "Passionate Ruby on Rails developer with a Master's degree in Computer Engineering."

# Social profiles (optional)
github_username: yhru

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/yhru" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/maxim-joseau" }

google_analytics: UA-NNNNNNNN-N
show_excerpts: false

# Custom settings
logo: "logo.png"
subtitle: "Software Engineering and Development"

remote_theme: "jekyll/minima"

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
